#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lpp.Dns.HealthCare.DataChecker.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    
    #line 2 "..\..\Views\Create.cshtml"
    using System.Reflection;
    
    #line default
    #line hidden
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Lpp;
    using Lpp.Dns.HealthCare.Controllers;
    
    #line 5 "..\..\Views\Create.cshtml"
    using Lpp.Dns.Portal;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Create.cshtml"
    using Lpp.Mvc;
    
    #line default
    #line hidden
    using Lpp.Mvc.Application;
    using Lpp.Mvc.Controls;
    
    #line 3 "..\..\Views\Create.cshtml"
    using Newtonsoft.Json;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Create.cshtml")]
    public partial class Create : System.Web.Mvc.WebViewPage<Lpp.Dns.HealthCare.DataChecker.Models.DataCheckerModel>
    {
        public Create()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Views\Create.cshtml"
   
    Assembly assembly = typeof(Lpp.Dns.General.Metadata.MetadataSearchRequestType).Assembly;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    var KOViewModel = true;     // indicates this page is built with KO templa" +
"tes\r\n</script>\r\n\r\n<script");

WriteLiteral(" id=\"RxSupTerm\"");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(">\r\n    <table id=\"RxSupGrid\">\r\n        <thead>\r\n            <tr>\r\n               " +
" <th>RxSup</th>\r\n            </tr>\r\n        </thead>\r\n        <tbody>\r\n\r\n       " +
"     <tr>\r\n                <td>\r\n                    <input type=\"checkbox\" data" +
"-bind=\"checked: RxSups\" value=\"0\" id=\"rxLessThanZero\" />\r\n                    <l" +
"abel for=\"rxLessThanZero\">&lt;0</label>\r\n                </td>\r\n            </tr" +
">\r\n\r\n            <tr>\r\n                <td>\r\n                    <input type=\"ch" +
"eckbox\" data-bind=\"checked: RxSups\" value=\"1\" id=\"rxSupZero\" />\r\n               " +
"     <label for=\"rxSupZero\">0-1</label>\r\n                </td>\r\n            </tr" +
">\r\n            <tr>\r\n                <td>\r\n                    <input type=\"chec" +
"kbox\" data-bind=\"checked: RxSups\" value=\"2\" id=\"rxSupTwo\" />\r\n                  " +
"  <label for=\"rxSupTwo\">2-30</label>\r\n                </td>\r\n            </tr>\r\n" +
"\r\n            <tr>\r\n                <td>\r\n                    <input type=\"check" +
"box\" data-bind=\"checked: RxSups\" value=\"3\" id=\"rxSupThirty\" />\r\n                " +
"    <label for=\"rxSupThirty\">31-60</label>\r\n                </td>\r\n            <" +
"/tr>\r\n            <tr>\r\n                <td>\r\n                    <input type=\"c" +
"heckbox\" data-bind=\"checked: RxSups\" value=\"4\" id=\"rxSupSixty\" />\r\n             " +
"       <label for=\"rxSupSixty\">61-90</label>\r\n                </td>\r\n           " +
" </tr>\r\n            <tr>\r\n                <td>\r\n                    <input type=" +
"\"checkbox\" data-bind=\"checked: RxSups\" value=\"5\" id=\"rxSupNinety\" />\r\n          " +
"          <label for=\"rxSupNinety\">&gt;90</label>\r\n                </td>\r\n      " +
"      </tr>\r\n            <tr>\r\n                <td>\r\n                    <input " +
"type=\"checkbox\" data-bind=\"checked: RxSups\" value=\"7\" id=\"rxSupMissing\" />\r\n    " +
"                <label for=\"rxSupMissing\">Missing</label>\r\n                </td>" +
"\r\n            </tr>\r\n\r\n        </tbody>\r\n    </table>\r\n\r\n</script>\r\n\r\n<script");

WriteLiteral(" id=\"RxAmtTerm\"");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(">\r\n    <table id=\"RxAmtGrid\">\r\n        <thead>\r\n            <tr>\r\n               " +
" <th>RxAmt</th>\r\n            </tr>\r\n        </thead>\r\n        <tbody>\r\n         " +
"   <tr>\r\n                <td>\r\n                    <input type=\"checkbox\" data-b" +
"ind=\"checked: RxAmounts\" value=\"0\" id=\"rxAmtLessThanZero\" />\r\n                  " +
"  <label for=\"rxAmtLessThanZero\">&lt;0</label>\r\n                </td>\r\n         " +
"   </tr>\r\n            <tr>\r\n                <td>\r\n                    <input typ" +
"e=\"checkbox\" data-bind=\"checked: RxAmounts\" value=\"1\" id=\"rxAmtZero\" />\r\n       " +
"             <label for=\"rxAmtZero\">0-1</label>\r\n                </td>\r\n        " +
"    </tr>\r\n            <tr>\r\n                <td>\r\n                    <input ty" +
"pe=\"checkbox\" data-bind=\"checked: RxAmounts\" value=\"2\" id=\"rxAmtTwoThrough30\" />" +
"\r\n                    <label for=\"rxAmtTwoThrough30\">2-30</label>\r\n             " +
"   </td>\r\n            </tr>\r\n            <tr>\r\n                <td>\r\n           " +
"         <input type=\"checkbox\" data-bind=\"checked: RxAmounts\" value=\"3\" id=\"rxA" +
"mtThirty\" />\r\n                    <label for=\"rxAmtThirty\">31-60</label>\r\n      " +
"          </td>\r\n            </tr>\r\n            <tr>\r\n                <td>\r\n    " +
"                <input type=\"checkbox\" data-bind=\"checked: RxAmounts\" value=\"4\" " +
"id=\"rxAmtSixty\" />\r\n                    <label for=\"rxAmtSixty\">61-90</label>\r\n " +
"               </td>\r\n            </tr>\r\n            <tr>\r\n                <td>\r" +
"\n                    <input type=\"checkbox\" data-bind=\"checked: RxAmounts\" value" +
"=\"5\" id=\"rxAmtNinety\" />\r\n                    <label for=\"rxAmtNinety\">91-120</l" +
"abel>\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n             " +
"   <td>\r\n                    <input type=\"checkbox\" data-bind=\"checked: RxAmount" +
"s\" value=\"6\" id=\"rxAmtOneTwenty\" />\r\n                    <label for=\"rxAmtOneTwe" +
"nty\">121-180</label>\r\n                </td>\r\n            </tr>\r\n            <tr>" +
"\r\n                <td>\r\n                    <input type=\"checkbox\" data-bind=\"ch" +
"ecked: RxAmounts\" value=\"7\" id=\"rxAmtOne180\" />\r\n                    <label for=" +
"\"rxAmtOne180\">&gt;180</label>\r\n                </td>\r\n            </tr>\r\n       " +
"     <tr>\r\n                <td>\r\n                    <input type=\"checkbox\" data" +
"-bind=\"checked: RxAmounts\" value=\"9\" id=\"rxAmtMissing\" />\r\n                    <" +
"label for=\"rxAmtMissing\">Missing</label>\r\n                </td>\r\n            </t" +
"r>\r\n\r\n        </tbody>\r\n    </table>\r\n</script>\r\n\r\n<script");

WriteLiteral(" id=\"PDXTerm\"");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(@">
    <table id=""PDXGrid"">
        <thead>
            <tr>
                <th>PDX</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <input type=""checkbox"" data-bind=""checked: PDXes"" value=""0"" id=""pdxPrinciple"" />
                    <label for=""pdxPrinciple"">Principle</label>
                </td>
            </tr>
            <tr>
                <td>
                    <input type=""checkbox"" data-bind=""checked: PDXes"" value=""1"" id=""pdxSecondary"" />
                    <label for=""pdxSecondary"">Secondary</label>
                </td>
            </tr>
            <tr>
                <td>
                    <input type=""checkbox"" data-bind=""checked: PDXes"" value=""2"" id=""pdxOther"" />
                    <label for=""pdxOther"">Other PDX</label>
                </td>
            </tr>
            <tr>
                <td>
                    <input type=""checkbox"" data-bind=""checked: PDXes"" value=""3"" id=""pdxMissing"" />
                    <label for=""pdxMissing"">Missing</label>
                </td>
            </tr>

        </tbody>
    </table>
</script>

<script");

WriteLiteral(" id=\"EncounterTypeTerm\"");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" >\r\n    <table id=\"EncounterTypeGrid\">\r\n        <thead>\r\n            <tr>\r\n      " +
"          <th>Encounter Type</th>\r\n            </tr>\r\n        </thead>\r\n        " +
"<tbody>\r\n            <tr>\r\n                <td>\r\n                    <input type" +
"=\"checkbox\" data-bind=\"checked: Encounters\" value=\"0\" id=\"encounterAll\" />\r\n    " +
"                <label for=\"encounterAll\">All</label>\r\n                </td>\r\n  " +
"          </tr>\r\n            <tr>\r\n                <td>\r\n                    <in" +
"put type=\"checkbox\" data-bind=\"checked: Encounters\" value=\"1\" id=\"encounterAmbul" +
"atoryVisit\" />\r\n                    <label for=\"encounterAmbulatoryVisit\">Ambula" +
"tory Visit (AV)</label>\r\n                </td>\r\n            </tr>\r\n            <" +
"tr>\r\n                <td>\r\n                    <input type=\"checkbox\" data-bind=" +
"\"checked: Encounters\" value=\"2\" id=\"encounterEmergencyDepartment\" />\r\n          " +
"          <label for=\"encounterEmergencyDepartment\">Emergency Department (ED)</l" +
"abel>\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n             " +
"   <td>\r\n                    <input type=\"checkbox\" data-bind=\"checked: Encounte" +
"rs\" value=\"3\" id=\"encounterInpatientHospitalStay\" />\r\n                    <label" +
" for=\"encounterInpatientHospitalStay\">Inpatient Hospital Stay (IP)</label>\r\n    " +
"            </td>\r\n            </tr>\r\n            <tr>\r\n                <td>\r\n  " +
"                  <input type=\"checkbox\" data-bind=\"checked: Encounters\" value=\"" +
"4\" id=\"encounterNonAcuteInstitutionalStay\" />\r\n                    <label for=\"e" +
"ncounterNonAcuteInstitutionalStay\">Non-Acute Institutional Stay (IS)</label>\r\n  " +
"              </td>\r\n            </tr>\r\n            <tr>\r\n                <td>\r\n" +
"                    <input type=\"checkbox\" data-bind=\"checked: Encounters\" value" +
"=\"5\" id=\"encounterOther\" />\r\n                    <label for=\"encounterOther\">Oth" +
"er Ambulatory Visit (OA)</label>\r\n                </td>\r\n            </tr>\r\n    " +
"        <tr>\r\n                <td>\r\n                    <input type=\"checkbox\" d" +
"ata-bind=\"checked: Encounters\" value=\"6\" id=\"encounterMissing\" />\r\n             " +
"       <label for=\"encounterMissing\">Missing</label>\r\n                </td>\r\n   " +
"         </tr>\r\n\r\n        </tbody>\r\n    </table>\r\n\r\n</script>\r\n\r\n<script");

WriteLiteral(" id=\"MetaDataTableTerm\"");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(@">
    <table id=""MetaDataGrid"">
        <thead>
            <tr>
                <th>Table</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <input type=""checkbox"" data-bind=""checked: Tables"" value=""0"" id=""tableDiagnosis"" />
                    <label for=""tableDiagnosis"">Diagnosis</label>
                </td>
            </tr>
            <tr>
                <td>
                    <input type=""checkbox"" data-bind=""checked: Tables"" value=""1"" id=""tableDispensing"" />
                    <label for=""tableDispensing"">Dispensing</label>
                </td>
            </tr>
            <tr>
                <td>
                    <input type=""checkbox"" data-bind=""checked: Tables"" value=""2"" id=""tableEncounter"" />
                    <label for=""tableEncounter"">Encounter</label>
                </td>
            </tr>
            <tr>
                <td>
                    <input type=""checkbox"" data-bind=""checked: Tables"" value=""3"" id=""tableEnrollment"" />
                    <label for=""tableEnrollment"">Enrollment</label>
                </td>
            </tr>
            <tr>
                <td>
                    <input type=""checkbox"" data-bind=""checked: Tables"" value=""4"" id=""tabelProcedure"" />
                    <label for=""tabelProcedure"">Procedure</label>
                </td>
            </tr>

        </tbody>
    </table>
</script>

<div");

WriteLiteral(" id=\"CodesTerm\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"label-groupbox\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" id=\"CodesGrid\"");

WriteLiteral(">\r\n            <thead>\r\n                <tr>\r\n                    <th");

WriteLiteral(" data-bind=\"visible: CodesTermType() == RequestCriteriaModels.CodesTermTypes.Diag" +
"nosis_ICD9Term\"");

WriteLiteral(">Diagnosis Codes</th>\r\n                    <th");

WriteLiteral(" data-bind=\"visible: CodesTermType() == RequestCriteriaModels.CodesTermTypes.Proc" +
"edure_ICD9Term\"");

WriteLiteral(">Procedure Codes</th>\r\n                    <th");

WriteLiteral(" data-bind=\"visible: CodesTermType() == RequestCriteriaModels.CodesTermTypes.NDCT" +
"erm\"");

WriteLiteral(">NDC Codes</th>\r\n                </tr>\r\n            </thead>\r\n            <tbody>" +
"\r\n                <tr>\r\n                    <td");

WriteLiteral(" data-bind=\"visible: CodesTermType() == RequestCriteriaModels.CodesTermTypes.Diag" +
"nosis_ICD9Term\"");

WriteLiteral(">\r\n                        <select");

WriteLiteral(" data-bind=\"value: CodeType\"");

WriteLiteral(">\r\n                            <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">(Any)</option>\r\n                            <option");

WriteLiteral(" value=\"09\"");

WriteLiteral(">ICD-9-CM</option>\r\n                            <option");

WriteLiteral(" value=\"10\"");

WriteLiteral(">ICD-10-CM</option>\r\n                            <option");

WriteLiteral(" value=\"11\"");

WriteLiteral(">ICD-11-CM</option>\r\n                            <option");

WriteLiteral(" value=\"C2\"");

WriteLiteral(" hidden>CPT Category II</option>\r\n                            <option");

WriteLiteral(" value=\"C3\"");

WriteLiteral(" hidden>CPT Category III</option>\r\n                            <option");

WriteLiteral(" value=\"C4\"");

WriteLiteral(" hidden>CPT-4 (i.e., HCPCS Level I)</option>\r\n                            <option" +
"");

WriteLiteral(" value=\"HC\"");

WriteLiteral(" hidden>HCPCS (i.e., HCPCS Level II)</option>\r\n                            <optio" +
"n");

WriteLiteral(" value=\"H3\"");

WriteLiteral(" hidden>HCPCS Level III</option>\r\n                            <option");

WriteLiteral(" value=\"LC\"");

WriteLiteral(" hidden>LOINC</option>\r\n                            <option");

WriteLiteral(" value=\"LO\"");

WriteLiteral(" hidden>Local Homegrown</option>\r\n                            <option");

WriteLiteral(" value=\"ND\"");

WriteLiteral(" hidden>NDC</option>\r\n                            <option");

WriteLiteral(" value=\"RE\"");

WriteLiteral(" hidden>Revenue</option>\r\n                            <option");

WriteLiteral(" value=\"SM\"");

WriteLiteral(">SNOMED CT</option>\r\n                            <option");

WriteLiteral(" value=\"OT\"");

WriteLiteral(">Other</option>\r\n                        </select>\r\n                    </td>\r\n  " +
"                  <td");

WriteLiteral(" data-bind=\"visible: CodesTermType() == RequestCriteriaModels.CodesTermTypes.Proc" +
"edure_ICD9Term\"");

WriteLiteral(">\r\n                        <select");

WriteLiteral(" data-bind=\"value: CodeType\"");

WriteLiteral(">\r\n                            <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">(Any)</option>\r\n                            <option");

WriteLiteral(" value=\"09\"");

WriteLiteral(">ICD-9-CM</option>\r\n                            <option");

WriteLiteral(" value=\"10\"");

WriteLiteral(">ICD-10-CM</option>\r\n                            <option");

WriteLiteral(" value=\"11\"");

WriteLiteral(">ICD-11-CM</option>\r\n                            <option");

WriteLiteral(" value=\"C2\"");

WriteLiteral(">CPT Category II</option>\r\n                            <option");

WriteLiteral(" value=\"C3\"");

WriteLiteral(">CPT Category III</option>\r\n                            <option");

WriteLiteral(" value=\"C4\"");

WriteLiteral(">CPT-4 (i.e., HCPCS Level I)</option>\r\n                            <option");

WriteLiteral(" value=\"HC\"");

WriteLiteral(">HCPCS (i.e., HCPCS Level II)</option>\r\n                            <option");

WriteLiteral(" value=\"H3\"");

WriteLiteral(">HCPCS Level III</option>\r\n                            <option");

WriteLiteral(" value=\"LC\"");

WriteLiteral(">LOINC</option>\r\n                            <option");

WriteLiteral(" value=\"LO\"");

WriteLiteral(">Local Homegrown</option>\r\n                            <option");

WriteLiteral(" value=\"ND\"");

WriteLiteral(">NDC</option>\r\n                            <option");

WriteLiteral(" value=\"RE\"");

WriteLiteral(">Revenue</option>\r\n                            <option");

WriteLiteral(" value=\"SM\"");

WriteLiteral(" hidden>SNOMED CT</option>\r\n                            <option");

WriteLiteral(" value=\"OT\"");

WriteLiteral(">Other</option>\r\n                        </select>\r\n                    </td>\r\n  " +
"                  <td");

WriteLiteral(" data-bind=\"visible: CodesTermType() == RequestCriteriaModels.CodesTermTypes.NDCT" +
"erm\"");

WriteLiteral(">\r\n                        &nbsp;\r\n                    </td>\r\n                </t" +
"r>\r\n                <tr>\r\n                    <td>\r\n                        <tex" +
"tarea");

WriteLiteral(" style=\"height: 70px; width: 95%;\"");

WriteLiteral(" data-bind=\"value: Codes\"");

WriteLiteral("></textarea><br />\r\n                        <input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" name=\"SearchTermMethod\"");

WriteLiteral(" data-bind=\"value: RequestCriteriaModels.SearchMethodTypes.ExactMatch, checked: S" +
"earchMethodType\"");

WriteLiteral(" /><span>Exact Match</span><br />\r\n                        <input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" name=\"SearchTermMethod\"");

WriteLiteral(" data-bind=\"value: RequestCriteriaModels.SearchMethodTypes.StartsWith, checked: S" +
"earchMethodType\"");

WriteLiteral(" /><span>Starts With</span><br />\r\n                    </td>\r\n                </t" +
"r>\r\n             </tbody>\r\n        </table>\r\n    </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" id=\"DataPartnerTerm\"");

WriteLiteral(" style=\"display: none\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" id=\"DataPartnersGrid\"");

WriteLiteral(">\r\n        <thead>\r\n            <tr>\r\n                <th");

WriteLiteral(" style=\"width: 24px;\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" onchange=\"SelectAll(this, \'DataPartnersTable\')\"");

WriteLiteral(" />\r\n                </th>\r\n                <th>Data Partner</th>\r\n            </" +
"tr>\r\n        </thead>\r\n        <tbody");

WriteLiteral(" id=\"DataPartnersTable\"");

WriteLiteral(" data-bind=\"foreach: ");

            
            #line 352 "..\..\Views\Create.cshtml"
                                                      Write(Newtonsoft.Json.JsonConvert.SerializeObject(Model.DataPartners));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n            <tr>\r\n                <td>\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" data-bind=\"value: Value, checked: $parent.DataPartners\"");

WriteLiteral(" />\r\n                </td>\r\n                <td>\r\n                    <span");

WriteLiteral(" data-bind=\"text: Key\"");

WriteLiteral("></span>&nbsp;(<span");

WriteLiteral(" data-bind=\"text: Value\"");

WriteLiteral("></span>)\r\n                </td>\r\n            </tr>\r\n        </tbody>\r\n    </tabl" +
"e>\r\n</div>\r\n\r\n<div");

WriteLiteral(" id=\"EthnicityTerm\"");

WriteLiteral(" style=\"display: none\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" id=\"EthnicityGrid\"");

WriteLiteral(">\r\n        <thead>\r\n            <tr>\r\n                <th");

WriteLiteral(" style=\"width: 24px;\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" onchange=\"SelectAll(this, \'EthnicityTable\')\"");

WriteLiteral(" />\r\n                </th>\r\n                <th>Ethnicity</th>\r\n            </tr>" +
"\r\n        </thead>\r\n        <tbody");

WriteLiteral(" id=\"EthnicityTable\"");

WriteLiteral(" data-bind=\"foreach: DataCheckerViewModels.EthnicityTerm.EthnicitiesList\"");

WriteLiteral(">\r\n            <tr>\r\n                <td>\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" data-bind=\"value: Value, checked: $parent.Ethnicities\"");

WriteLiteral(" />\r\n                </td>\r\n                <td>\r\n                    <span");

WriteLiteral(" data-bind=\"text: Key\"");

WriteLiteral("></span>\r\n                </td>\r\n            </tr>\r\n        </tbody>\r\n    </table" +
">\r\n</div>\r\n\r\n<div");

WriteLiteral(" id=\"MetricTerm\"");

WriteLiteral(" style=\"display: none\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" id=\"MetricGrid\"");

WriteLiteral(">\r\n        <thead>\r\n            <tr>\r\n                <th");

WriteLiteral(" style=\"width: 24px;\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" onchange=\"SelectAll(this, \'MetricsTable\')\"");

WriteLiteral(" />\r\n                </th>\r\n                <th>Metric</th>\r\n            </tr>\r\n " +
"       </thead>\r\n        <tbody");

WriteLiteral(" id=\"MetricsTable\"");

WriteLiteral(" data-bind=\"foreach: MetricsList\"");

WriteLiteral(">\r\n            <tr>\r\n                <td>\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" data-bind=\"value: Value, checked: $parent.Metrics\"");

WriteLiteral(" />\r\n                </td>\r\n                <td>\r\n                    <span");

WriteLiteral(" data-bind=\"text: Key\"");

WriteLiteral(" ></span>\r\n                </td>\r\n            </tr>\r\n        </tbody>\r\n    </tabl" +
"e>\r\n</div>\r\n\r\n<div");

WriteLiteral(" id=\"RaceTerm\"");

WriteLiteral(" style=\"display: none\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" id=\"RaceGrid\"");

WriteLiteral(">\r\n        <thead>\r\n            <tr>\r\n                <th");

WriteLiteral(" style=\"width: 24px;\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" onchange=\"SelectAll(this, \'RaceTable\')\"");

WriteLiteral(" />\r\n                </th>\r\n                <th>Race</th>\r\n            </tr>\r\n   " +
"     </thead>\r\n        <tbody");

WriteLiteral(" id=\"RaceTable\"");

WriteLiteral(" data-bind=\"foreach: DataCheckerViewModels.RaceTerm.RacesList\"");

WriteLiteral(">\r\n            <tr>\r\n                <td>\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" data-bind=\"value: Value, checked: $parent.Races\"");

WriteLiteral(" />\r\n                </td>\r\n                <td>\r\n                    <span");

WriteLiteral(" data-bind=\"text: Key\"");

WriteLiteral(" ></span>\r\n                </td>\r\n            </tr>\r\n        </tbody>\r\n    </tabl" +
"e>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"DataChecker ui-form\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui-form\"");

WriteLiteral(">\r\n        <fieldset");

WriteLiteral(" id=\"fsCriteria\"");

WriteLiteral(">\r\n            <legend");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral("></legend>\r\n");

WriteLiteral("            ");

            
            #line 438 "..\..\Views\Create.cshtml"
       Write(Html.HiddenFor(m => m.CriteriaGroupsJSON));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" id=\'errorLocation\'");

WriteLiteral(" style=\"font-size: small; color: Gray;\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"ui-groupbox\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui-groupbox-header\"");

WriteLiteral(">\r\n                    <span>Data Checker Criteria</span>\r\n                </div>" +
"\r\n                <ol");

WriteLiteral(" data-bind=\"foreach: RequestCriteria.Criterias\"");

WriteLiteral(">\r\n                    <li>\r\n                        <ul");

WriteLiteral(" data-bind=\"foreach: RequestTerms\"");

WriteLiteral(">\r\n                            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" data-bind=\"template: { name: TemplateName }\"");

WriteLiteral("></div>\r\n                            </li>\r\n                        </ul>\r\n      " +
"              </li>\r\n                </ol>\r\n                <br");

WriteLiteral(" style=\"clear: both;\"");

WriteLiteral(" />\r\n            </div>\r\n        </fieldset>\r\n    </div>\r\n</div>\r\n\r\n");

WriteLiteral("\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 18172), Tuple.Create("\"", 18235)
            
            #line 460 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 18178), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "Models/RequestCriteria.js")
            
            #line default
            #line hidden
, 18178), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 18278), Tuple.Create("\"", 18334)
            
            #line 461 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 18284), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "Models/Criteria.js")
            
            #line default
            #line hidden
, 18284), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 18377), Tuple.Create("\"", 18430)
            
            #line 462 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 18383), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "Models/Terms.js")
            
            #line default
            #line hidden
, 18383), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 18473), Tuple.Create("\"", 18540)
            
            #line 463 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 18479), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "ViewModels/RequestCriteria.js")
            
            #line default
            #line hidden
, 18479), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 18583), Tuple.Create("\"", 18643)
            
            #line 464 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 18589), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "ViewModels/Criteria.js")
            
            #line default
            #line hidden
, 18589), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 18686), Tuple.Create("\"", 18743)
            
            #line 465 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 18692), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "ViewModels/Terms.js")
            
            #line default
            #line hidden
, 18692), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 18811), Tuple.Create("\"", 18878)
            
            #line 467 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 18817), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "ViewModels/Terms/CodesTerm.js")
            
            #line default
            #line hidden
, 18817), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 18921), Tuple.Create("\"", 18986)
            
            #line 468 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 18927), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "Models/Terms/DataPartner.js")
            
            #line default
            #line hidden
, 18927), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 19029), Tuple.Create("\"", 19098)
            
            #line 469 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 19035), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "ViewModels/Terms/DataPartner.js")
            
            #line default
            #line hidden
, 19035), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 19141), Tuple.Create("\"", 19204)
            
            #line 470 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 19147), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "Models/Terms/Ethnicity.js")
            
            #line default
            #line hidden
, 19147), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 19247), Tuple.Create("\"", 19314)
            
            #line 471 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 19253), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "ViewModels/Terms/Ethnicity.js")
            
            #line default
            #line hidden
, 19253), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 19357), Tuple.Create("\"", 19417)
            
            #line 472 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 19363), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "Models/Terms/Metric.js")
            
            #line default
            #line hidden
, 19363), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 19460), Tuple.Create("\"", 19524)
            
            #line 473 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 19466), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "ViewModels/Terms/Metric.js")
            
            #line default
            #line hidden
, 19466), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 19567), Tuple.Create("\"", 19625)
            
            #line 474 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 19573), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "Models/Terms/Race.js")
            
            #line default
            #line hidden
, 19573), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 19668), Tuple.Create("\"", 19730)
            
            #line 475 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 19674), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "ViewModels/Terms/Race.js")
            
            #line default
            #line hidden
, 19674), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 19773), Tuple.Create("\"", 19834)
            
            #line 476 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 19779), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "Models/Terms/Project.js")
            
            #line default
            #line hidden
, 19779), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 19877), Tuple.Create("\"", 19942)
            
            #line 477 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 19883), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "ViewModels/Terms/Project.js")
            
            #line default
            #line hidden
, 19883), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 19985), Tuple.Create("\"", 20052)
            
            #line 478 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 19991), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "Models/Terms/RequestStatus.js")
            
            #line default
            #line hidden
, 19991), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 20095), Tuple.Create("\"", 20166)
            
            #line 479 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 20101), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "ViewModels/Terms/RequestStatus.js")
            
            #line default
            #line hidden
, 20101), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 20209), Tuple.Create("\"", 20276)
            
            #line 480 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 20215), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "ViewModels/Terms/DateRange.js")
            
            #line default
            #line hidden
, 20215), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 20319), Tuple.Create("\"", 20385)
            
            #line 481 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 20325), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "Models/Terms/WorkplanType.js")
            
            #line default
            #line hidden
, 20325), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 20428), Tuple.Create("\"", 20498)
            
            #line 482 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 20434), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "ViewModels/Terms/WorkplanType.js")
            
            #line default
            #line hidden
, 20434), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 20541), Tuple.Create("\"", 20610)
            
            #line 483 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 20547), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "Models/Terms/RequesterCenter.js")
            
            #line default
            #line hidden
, 20547), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 20653), Tuple.Create("\"", 20726)
            
            #line 484 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 20659), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "ViewModels/Terms/RequesterCenter.js")
            
            #line default
            #line hidden
, 20659), false)
);

WriteLiteral("></script>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 20771), Tuple.Create("\"", 20828)
            
            #line 486 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 20777), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "Models/Terms/pdx.js")
            
            #line default
            #line hidden
, 20777), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 20871), Tuple.Create("\"", 20932)
            
            #line 487 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 20877), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "ViewModels/Terms/pdx.js")
            
            #line default
            #line hidden
, 20877), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 20975), Tuple.Create("\"", 21034)
            
            #line 488 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 20981), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "Models/Terms/rxamt.js")
            
            #line default
            #line hidden
, 20981), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 21077), Tuple.Create("\"", 21140)
            
            #line 489 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 21083), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "ViewModels/Terms/rxamt.js")
            
            #line default
            #line hidden
, 21083), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 21183), Tuple.Create("\"", 21242)
            
            #line 490 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 21189), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "Models/Terms/rxsup.js")
            
            #line default
            #line hidden
, 21189), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 21285), Tuple.Create("\"", 21348)
            
            #line 491 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 21291), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "ViewModels/Terms/rxsup.js")
            
            #line default
            #line hidden
, 21291), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 21391), Tuple.Create("\"", 21458)
            
            #line 492 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 21397), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "Models/Terms/metadatatable.js")
            
            #line default
            #line hidden
, 21397), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 21501), Tuple.Create("\"", 21572)
            
            #line 493 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 21507), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "ViewModels/Terms/metadatatable.js")
            
            #line default
            #line hidden
, 21507), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 21615), Tuple.Create("\"", 21682)
            
            #line 494 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 21621), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "Models/Terms/encountertype.js")
            
            #line default
            #line hidden
, 21621), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 21725), Tuple.Create("\"", 21796)
            
            #line 495 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 21731), Tuple.Create<System.Object, System.Int32>(this.Url.Resource(assembly, "ViewModels/Terms/encountertype.js")
            
            #line default
            #line hidden
, 21731), false)
);

WriteLiteral("></script>\r\n\r\n");

WriteLiteral("\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 21865), Tuple.Create("\"", 21909)
            
            #line 498 "..\..\Views\Create.cshtml"
, Tuple.Create(Tuple.Create("", 21871), Tuple.Create<System.Object, System.Int32>(this.Resource("ViewModels/Create.js")
            
            #line default
            #line hidden
, 21871), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    function SelectAll(checker, table) {
        // Find the table's checkboxes, and if in the wrong state, ""click it"".
        // Since the checkbox is two-way bound to the list of values, and not a boolean, setting
        // the checked attribute of the checkbox and raising the change event DOES NOT work, 
        // rather we just need to force a click action to cause the underlying list to update
        $(""#"" + table + "" tr input[type=checkbox]"").each(function(){    
            if (this.checked != checker.checked)
                $(this).click();
        });
    }

    jQuery(document).ready(function () {
        // initialize the viewmodel
        //create.cshtml
        var json = ");

            
            #line 516 "..\..\Views\Create.cshtml"
               Write(Html.Raw(HttpUtility.HtmlDecode(Model.CriteriaGroupsJSON) + ";"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        DataChecker.Create.init(json, $(\"#fsCriteria\"), $(\"#CriteriaGroupsJSON\"" +
"));\r\n    });\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
