// <auto-generated />
namespace Lpp.Dns.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddMetadataMangePermission : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMetadataMangePermission));
        
        string IMigrationMetadata.Id
        {
            get { return "201609161312055_AddMetadataMangePermission"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
